name: pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  auto_route_generator: ^8.0.0
  bloc: ^8.1.4
  build_runner: ^2.4.10
  collection: ^1.18.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_gen: ^5.5.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  get_it: ^7.7.0
  google_fonts: ^4.0.4
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  pokeapi: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"